export type ValueType =
  | 'input'
  | 'number'
  | 'password'
  | 'money'
  | 'textarea'
  | 'date'
  | 'dateTime'
  | 'dateWeek'
  | 'dateMonth'
  | 'dateQuarter'
  | 'dateYear'
  | 'dateRange'
  | 'dateTimeRange'
  | 'time'
  | 'timeRange'
  | 'text'
  | 'select'
  | 'treeSelect'
  | 'checkbox'
  | 'rate'
  | 'radio'
  | 'radioButton'
  | 'progress'
  | 'percent'
  | 'digit'
  | 'second'
  | 'avatar'
  | 'code'
  | 'switch'
  | 'fromNow'
  | 'image'
  | 'jsonCode'
  | 'color'
  | 'cascader'
  | 'segmented'
  | 'group'
  | 'formList'
  | 'formSet'
  | 'divider'
  | 'dependency'
  | 'file'

export interface ProFieldProps {
  value?: any
  valueType?: ValueType
  fieldProps?: Record<string, any>
  mode?: 'read' | 'edit'
}
